name: Save cache
inputs:
  key:
    required: true
    description: Prefix to the cache key, should be retrieve from `cache-restore` composite action.
    type: string
  additional-paths:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Save cache
    uses: actions/cache/save@v4
    with:
      key: ${{ inputs.key }}
      path: |
        .cache
        .nx/cache
        node_modules/.cache
        packages/*/node_modules/.cache
        ${{ inputs.additional-paths }}