name: Restore cache
inputs:
  key:
    required: true
    description: Prefix to the cache key
    type: string
  additional-paths:
    required: false
    type: string
outputs:
  cache-primary-key:
    description: actions/cache/restore cache-primary-key outputs proxy
    value: ${{ steps.restore-cache.outputs.cache-primary-key }}
  cache-hit:
    description: String bool indicating whereas cache has been directly or indirectly hit
    value: ${{ steps.restore-cache.outputs.cache-hit != 'false' || steps.restore-cache.outputs.cache-matched-key != '' }}

runs:
  using: "composite"
  steps:
    - name: Restore Storybook build cache
      uses: actions/cache/restore@v4
      id: restore-cache
      with:
        path: |
          .cache
          .nx/cache
          node_modules/.cache
          packages/*/node_modules/.cache
          ${{ inputs.additional-paths }}
        key: ${{ inputs.key }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: ${{ inputs.key }}-${{ github.ref_name }}-