name: Yarn Install

runs:
  using: "composite"
  steps:
    - name: Cache primary key builder
      id: globals
      shell: bash
      run: |
        local_node_version=18
        echo "ACTION_SHELL=bash" >> "${GITHUB_OUTPUT}"
        echo "NODE_VERSION=$local_node_version" >> "${GITHUB_OUTPUT}"
        echo "CACHE_KEY_PREFIX=node_modules-cache-node-$( echo $local_node_version )-${{ hashFiles('yarn.lock') }}"  >> "${GITHUB_OUTPUT}"
    - name: Setup Node.js and get yarn cache
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.globals.outputs.NODE_VERSION }}
    # Could use changed files to detect updates to package.json and lockfile ?
    - name: Restore node_modules
      id: cache-node-modules
      uses: actions/cache/restore@v4
      with:
        key: ${{ steps.globals.outputs.CACHE_KEY_PREFIX }}-${{github.sha}}
        restore-keys: ${{ steps.globals.outputs.CACHE_KEY_PREFIX }}-
        path: |
          node_modules
          packages/*/node_modules
    - name: Install Dependencies ${{ steps.cache-node-modules.outputs.cache-hit != 'true' && steps.cache-node-modules.outputs.cache-matched-key == '' }}
      if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' && steps.cache-node-modules.outputs.cache-matched-key == '' }}
      shell: ${{ steps.globals.outputs.ACTION_SHELL }}
      run: |
        yarn config set enableHardenedMode true
        yarn --immutable --check-cache
    - name: Save cache
      if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' && steps.cache-node-modules.outputs.cache-matched-key == '' }}
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache-node-modules.outputs.cache-primary-key }}
        path: |
          node_modules
          packages/*/node_modules
      