name: CI E2E Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run-e2e'))
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Check for changed files
      id: changed-files
      uses: tj-actions/changed-files@v11
      with:
        files: |
          packages/**
          playwright.config.ts
          .github/workflows/ci-e2e.yml

    - name: Skip if no relevant changes
      if: steps.changed-files.outputs.any_changed == 'false'
      run: echo "No relevant changes detected. Marking as valid."

    - name: Install dependencies
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: ./.github/workflows/actions/yarn-install
    - name: Install Playwright Browsers
      if: steps.changed-files.outputs.any_changed == 'true'
      run: npx nx setup twenty-e2e-testing
    - name: Run Playwright tests
      if: steps.changed-files.outputs.any_changed == 'true'
      run: npx nx test twenty-e2e-testing
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
