name: CI Shared
on:
  push:
    branches:
      - main
    
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shared-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
    strategy:
      matrix:
        task: [lint, typecheck, test]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Fetch custom Github Actions and base branch history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for changed files
        id: changed-files
        uses: tj-actions/changed-files@v11
        with:
          files: |
            packages/twenty-shared/**
      - name: Skip if no relevant changes
        if: steps.changed-files.outputs.any_changed == 'false'
        run: echo "No relevant changes. Skipping CI."
      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/workflows/actions/yarn-install
      - name: Run ${{ matrix.task }} task
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/workflows/actions/nx-affected
        with:
          tag: scope:frontend
          tasks: ${{ matrix.task }}
